#!/bin/bash
LOG_ROOT=~/log/reportrepocommit
COMMITLOG="$LOG_ROOT/repocommitlog.log"
BUILDLOG="$LOG_ROOT/build.log"

### change below branches for your repo
BRANCHES=("origin/platform/android/main" \
		  "origin/platform/android/main2")

# echo ${BRANCHES[1]}

# Global variables set-up
DEBUG=1
TEST_RUN=0
DAY_TIME_PERIOD=1

#-----------------------------------------------------------------------------
pr_dbg(){
	if [ "$DEBUG" == "1" ]; then
		echo $1
	fi
}
# update repo
update_repo() {
	repo forall -p -c git remote update |  tee $BUILDLOG
}

generate_log(){
	echo "" | tee $COMMITLOG
	for branch in "${BRANCHES[@]}"
	do
		echo "" | tee -a $COMMITLOG
		echo "###########################################################################." | tee -a $COMMITLOG
		echo "Branch: $branch" | tee -a $COMMITLOG
		echo "###########################################################################." | tee -a $COMMITLOG
		repo forall -p -c git log --format=%h:%an:%cD:%s"." --since="yesterday" $branch | tee -a $COMMITLOG
	done
}

send_report(){
	mutt -s "Daily commit report" $1 < $COMMITLOG
}

###############################################################################
# Start main function
###############################################################################
TOPDIR=(`pwd`)
if [ ! -d ".repo" ]; then
	echo "Run the script on TOP directoryh of repo"
	exit
fi

if [ "$DAY_TIME_PERIOD" == "1" ]; then
	TIME_OPERATOR="%j"  # day
	pr_dbg "Loop period: Day"
else
	TIME_OPERATOR="%M"  # Second for test
	pr_dbg "Loop period: Second"
fi
CURRENT=`date "+$TIME_OPERATOR"`

RUN_SCRIPT=0
mkdir -p $LOG_ROOT
while [ 1 ]; do
	if [ "$CURRENT" != `date "+$TIME_OPERATOR"` ]; then
		pr_dbg "Time expired"
		pr_dbg "CURRENT: $CURRENT"
		CURRENT=`date "+$TIME_OPERATOR"`
		pr_dbg "NEXT: $CURRENT"
		RUN_SCRIPT=1
	fi

	if [ "$TEST_RUN" == "1" ]; then
		pr_dbg "Triggered test"
		RUN_SCRIPT=1
	fi

	# Execute main function
	if [ "$RUN_SCRIPT" == "1" ]; then
		pr_dbg "Running script..."

		update_repo
		generate_log
		send_report denny.ds.yang@gmail.com 

		pr_dbg "Finished script..."
	fi
	RUN_SCRIPT=0
	if [ "$TEST_RUN" == "1" ]; then
		exit
	fi
done
exit

